services:
    ibexa.cache_pool:
        # As we support custom TagAware services, we set class as interface here so lazy class is "correct"
        class: Symfony\Component\Cache\Adapter\TagAwareAdapterInterface
        factory: ['@Ibexa\Bundle\Core\ApiLoader\CacheFactory', getCachePool]
        arguments: ['@ibexa.config.resolver']

    Ibexa\Bundle\Core\ApiLoader\CacheFactory:
        class: Ibexa\Bundle\Core\ApiLoader\CacheFactory
        calls:
            - [setContainer, ["@service_container"]]

    Ibexa\Bundle\Core\Cache\Warmer\ProxyCacheWarmer:
        arguments:
            - '@Ibexa\Core\Repository\ProxyFactory\ProxyGeneratorInterface'
        tags:
            - { name: kernel.cache_warmer }
