services:
    Ibexa\Bundle\RepositoryInstaller\Migration\InstallSchemaMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\AddUrlAliasMlLinkIndexMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\RenameSchemaTo5_0Migration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\ImportDataMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\FixLegacyIdentifiersMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\AddContentAlwaysAvailableColumnsMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\AddLanguageTranslationTablesMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\AddSearchObjectWordLinkLanguageIdColumnsMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\AddUrlAliasAlwaysAvailableColumnMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\RepositoryInstaller\Migration\DropLanguageBitmaskColumnsMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }
