parameters:
    ibexa.kernel.root_dir: "%kernel.project_dir%/vendor/ibexa/core"

    # API
    ibexa.kernel.proxy_cache_dir: '%kernel.cache_dir%/repository/proxy'

    # Using legacy storage engine for data compatibility with 4.x
    ibexa.api.storage_engine.default: legacy
    ibexa.api.search_engine.default: legacy

services:
    # API
    Ibexa\Bundle\Core\ApiLoader\RepositoryFactory:
        deprecated:
            package: 'ibexa/core'
            version: '5.0'
            message: 'Since ibexa/core 5.0: The "%service_id%" service is deprecated and will be removed in 6.0. Use Ibexa\Core\Base\Container\ApiLoader\RepositoryFactory instead'
        arguments:
            $configResolver: '@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface'
            $policyMap: '%ibexa.api.role.policy_map%'
            $languageResolver: '@Ibexa\Contracts\Core\Repository\LanguageResolver'
            $repositoryConfigurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'
            $logger: "@?logger"

    Ibexa\Bundle\Core\ApiLoader\StorageEngineFactory:
        arguments:
            $repositoryConfigurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'

    ibexa.api.persistence_handler:
        #To disable cache, switch alias to Ibexa\Contracts\Core\Persistence\Handler
        alias: Ibexa\Core\Persistence\Cache\Handler

    Ibexa\Contracts\Core\Persistence\Handler:
        factory: ['@Ibexa\Bundle\Core\ApiLoader\StorageEngineFactory', buildStorageEngine]
        public: false

    Ibexa\Bundle\Core\ApiLoader\SearchEngineFactory:
        arguments:
            $repositoryConfigurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'

    Ibexa\Bundle\Core\ApiLoader\SearchEngineIndexerFactory:
            arguments:
                $repositoryConfigurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'

    ibexa.spi.search:
        alias: Ibexa\Contracts\Core\Search\VersatileHandler

    ibexa.spi.search.indexer:
        alias: Ibexa\Core\Search\Common\Indexer

    Ibexa\Contracts\Core\Search\VersatileHandler:
        class: Ibexa\Contracts\Core\Search\VersatileHandler
        factory: ['@Ibexa\Bundle\Core\ApiLoader\SearchEngineFactory', buildSearchEngine]
        public: false
        lazy: true

    Ibexa\Core\Search\Common\Indexer:
        class: Ibexa\Core\Search\Common\Indexer
        factory: ['@Ibexa\Bundle\Core\ApiLoader\SearchEngineIndexerFactory', buildSearchEngineIndexer]
        public: false

    # Redefine background indexer to the one provided here which works on kernel/console.terminate.
    Ibexa\Bundle\Core\EventListener\BackgroundIndexingTerminateListener:
        class: Ibexa\Bundle\Core\EventListener\BackgroundIndexingTerminateListener
        arguments:
            - '@ibexa.api.persistence_handler'
            - '@ibexa.spi.search'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\Contracts\Core\Search\Content\IndexerGateway:
        alias: Ibexa\Core\Search\Legacy\Content\IndexerGateway
