parameters:
    # Constant authentication execution time in seconds (float). Blocks timing attacks.
    # Must be larger than expected real execution time, with a good margin.
    # If set to zero, constant time authentication is disabled. Do not do this on production environments.
    ibexa.security.authentication.constant_auth_time: !php/const Ibexa\Bundle\Core\DependencyInjection\Compiler\SecurityPass::CONSTANT_AUTH_TIME_DEFAULT

services:
    Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider:
        class: Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    Ibexa\Core\MVC\Symfony\Security\User\EmailProvider:
        class: Ibexa\Core\MVC\Symfony\Security\User\EmailProvider
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    Ibexa\Core\MVC\Symfony\Security\UserChecker:
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'

    Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter:
        class: Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter:
        class: Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    Ibexa\Core\MVC\Symfony\Controller\SecurityController:
        public: true
        class: Ibexa\Core\MVC\Symfony\Controller\SecurityController
        arguments: ["@twig", '@ibexa.config.resolver', "@security.authentication_utils"]

    Ibexa\Core\MVC\Symfony\Security\EventListener\SecurityListener:
        class: Ibexa\Core\MVC\Symfony\Security\EventListener\SecurityListener
        arguments:
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@ibexa.config.resolver'
            - "@event_dispatcher"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "%fragment.path%"
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\Core\MVC\Symfony\Security\Authentication\GuardRepositoryAuthenticationProvider:
        decorates: security.authentication.provider.guard
        calls:
            - ['setPermissionResolver', ['@Ibexa\Contracts\Core\Repository\PermissionResolver']]

    ibexa.security.user_provider: '@Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider'
    ibexa.security.user_provider.username: '@Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider'
    ibexa.security.user_provider.email: '@Ibexa\Core\MVC\Symfony\Security\User\EmailProvider'
