services:
    ezpublish.urlwildcard_router:
        class: Ibexa\Core\MVC\Symfony\Routing\UrlWildcardRouter
        public: true
        arguments:
          - '@ibexa.api.service.url_wildcard'
          - '@Ibexa\Core\MVC\Symfony\Routing\Generator\UrlAliasGenerator'
          - '@router.request_context'
        calls:
          - [setLogger, ['@?logger']]
        tags:
          - { name: router, priority: 210 }
