<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Contracts\Core\Repository\Values\Content;

use Ibexa\Contracts\Core\Repository\Values\ValueObject;

/**
 * This class represents a url alias in the repository.
 *
 * @property-read string $id A unique identifier for the alias
 * @property-read int $type The type of the URL Alias i.e. one of URLAlias::LOCATION, URLAlias::RESOURCE, URLAlias::VIRTUAL
 * @property-read mixed $destination If type = URLAlias::LOCATION it is a Location id otherwise a string (e.g. /content/search)
 * @property-read string $path the alias path
 * @property-read string[] $languageCodes the languages for which this alias is valid
 * @property-read bool $alwaysAvailable Fallback indicator for other languages
 * @property-read bool $isHistory Indicates that this alias was autogenerated for an in the meanwhile archived version of the content
 * @property-read bool $isCustom If false this alias was autogenerated otherwise manuel created
 * @property-read bool $forward Indicates if the url should be redirected
 */
class URLAlias extends ValueObject
{
    public const int LOCATION = 0;
    public const int RESOURCE = 1;
    public const int VIRTUAL = 2;

    /**
     * A unique identifier for the alias
     * (in legacy implementation this would be <parentid>-<md5text>).
     *
     * Note: currently this will only be unique when $isHistory flag is false.
     */
    protected string $id;

    /**
     * The type of the URL Alias i.e. one of URLAlias::LOCATION, URLAlias::RESOURCE, URLAlias::VIRTUAL.
     */
    protected int $type;

    /**
     * If type = URLAlias::LOCATION it is a Location id
     * otherwise a string (e.g. /content/search).
     */
    protected string|int $destination;

    /**
     * the full path of the alias.
     */
    protected string $path;

    /**
     * The languageCodes for which this path is valid.
     *
     * @var string[]
     */
    protected array $languageCodes = [];

    /**
     * Fallback indicator for other languages.
     */
    protected bool $alwaysAvailable = false;

    /**
     * Indicates that this alias was autogenerated for an in the meanwhile archived version of the content.
     */
    protected bool $isHistory = false;

    /**
     * If false this alias was autogenerated otherwise manually created.
     */
    protected bool $isCustom = false;

    /**
     * Indicates if the url should be redirected.
     */
    protected bool $forward = false;
}
