<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */

namespace Ibexa\Tests\Integration\Core\Repository\FieldType;

use DateTime;
use Ibexa\Contracts\Core\Repository\Exceptions\InvalidArgumentException;
use Ibexa\Contracts\Core\Repository\Values\Content\Field;
use Ibexa\Core\FieldType\Time\Value as TimeValue;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;

/**
 * Integration test for use field type.
 */
#[Group('integration')]
#[Group('field-type')]
class TimeIntegrationTest extends SearchBaseIntegrationTestCase
{
    /**
     * Get name of tested field type.
     *
     * @return string
     */
    public function getTypeName(): string
    {
        return 'ibexa_time';
    }

    /**
     * {@inheritdoc}
     */
    protected function supportsLikeWildcard($value): bool
    {
        return false;
    }

    /**
     * Get expected settings schema.
     *
     * @return array
     */
    public function getSettingsSchema()
    {
        return [
            'useSeconds' => [
                'type' => 'bool',
                'default' => false,
            ],
            'defaultType' => [
                'type' => 'choice',
                'default' => 0,
            ],
        ];
    }

    /**
     * Get a valid $fieldSettings value.
     *
     * @return mixed
     */
    public function getValidFieldSettings()
    {
        return [
            'useSeconds' => false,
            'defaultType' => 0,
        ];
    }

    /**
     * Get $fieldSettings value not accepted by the field type.
     *
     * @return mixed
     */
    public function getInvalidFieldSettings()
    {
        return [
            'somethingUnknown' => 0,
        ];
    }

    /**
     * Get expected validator schema.
     *
     * @return array
     */
    public function getValidatorSchema()
    {
        return [];
    }

    /**
     * Get a valid $validatorConfiguration.
     *
     * @return mixed
     */
    public function getValidValidatorConfiguration()
    {
        return [];
    }

    /**
     * Get $validatorConfiguration not accepted by the field type.
     *
     * @return mixed
     */
    public function getInvalidValidatorConfiguration()
    {
        return [
            'unknown' => ['value' => 42],
        ];
    }

    /**
     * Get initial field data for valid object creation.
     *
     * @return mixed
     */
    public function getValidCreationFieldData()
    {
        // We may only create times from timestamps here, since storing will
        // loose information about the timezone.
        return new TimeValue(3661);
    }

    /**
     * Get name generated by the given field type (via fieldType->getName()).
     *
     * @return string
     */
    public function getFieldName(): string
    {
        return '1:01:01 am';
    }

    /**
     * Asserts that the field data was loaded correctly.
     *
     * Asserts that the data provided by {@link getValidCreationFieldData()}
     * was stored and loaded correctly.
     *
     * @param \Ibexa\Contracts\Core\Repository\Values\Content\Field $field
     */
    public function assertFieldDataLoadedCorrect(Field $field)
    {
        self::assertInstanceOf(
            TimeValue::class,
            $field->value
        );

        $expectedData = [
            'time' => 3661,
        ];
        $this->assertPropertiesCorrect(
            $expectedData,
            $field->value
        );
    }

    public static function provideInvalidCreationFieldData(): array
    {
        return [
            [
                'Some unknown date format', InvalidArgumentException::class,
            ],
        ];
    }

    /**
     * Get update field externals data.
     *
     * @return \Ibexa\Core\FieldType\Time\Value
     */
    public function getValidUpdateFieldData()
    {
        return TimeValue::fromTimestamp(12345678);
    }

    /**
     * Get externals updated field data values.
     *
     * This is a PHPUnit data provider
     *
     * @return array
     */
    public function assertUpdatedFieldDataLoadedCorrect(Field $field)
    {
        self::assertInstanceOf(
            TimeValue::class,
            $field->value
        );

        $dateTime = new DateTime('@12345678');
        $expectedData = [
            'time' => $dateTime->getTimestamp() - $dateTime->setTime(0, 0, 0)->getTimestamp(),
        ];
        $this->assertPropertiesCorrect(
            $expectedData,
            $field->value
        );
    }

    public static function provideInvalidUpdateFieldData(): array
    {
        return self::provideInvalidCreationFieldData();
    }

    /**
     * Tests failing content update.
     *
     * @param mixed $failingValue
     * @param string $expectedException
     */
    #[DataProvider('provideInvalidUpdateFieldData')]
    public function testUpdateContentFails($failingValue, $expectedException)
    {
        return [
            [
                'Some unknown date format', InvalidArgumentException::class,
            ],
        ];
    }

    /**
     * Asserts the the field data was loaded correctly.
     *
     * Asserts that the data provided by {@link getValidCreationFieldData()}
     * was copied and loaded correctly.
     *
     * @param \Ibexa\Contracts\Core\Repository\Values\Content\Field $field
     */
    public function assertCopiedFieldDataLoadedCorrectly(Field $field)
    {
        self::assertInstanceOf(
            TimeValue::class,
            $field->value
        );

        $expectedData = [
            'time' => 3661,
        ];
        $this->assertPropertiesCorrect(
            $expectedData,
            $field->value
        );
    }

    /**
     * Get data to test to hash method.
     *
     * This is a PHPUnit data provider
     *
     * The returned records must have the the original value assigned to the
     * first index and the expected hash result to the second. For example:
     *
     * <code>
     * array(
     *      array(
     *          new MyValue( true ),
     *          array( 'myValue' => true ),
     *      ),
     *      // ...
     * );
     * </code>
     *
     * @return array
     */
    public static function provideToHashData(): array
    {
        $timestamp = 123456;
        $dateTime = new DateTime("@{$timestamp}");

        return [
            [
                TimeValue::fromTimestamp($timestamp),
                $dateTime->getTimestamp() - $dateTime->setTime(0, 0, 0)->getTimestamp(),
            ],
        ];
    }

    /**
     * Get expectations for the fromHash call on our field value.
     *
     * This is a PHPUnit data provider
     *
     * @return array
     */
    public static function provideFromHashData(): array
    {
        return [
            [
                3661,
                new TimeValue(3661),
            ],
        ];
    }

    /**
     * @return array<mixed>
     */
    public static function providerForTestIsEmptyValue(): array
    {
        return [
            [new TimeValue()],
        ];
    }

    /**
     * @return array<mixed>
     */
    public static function providerForTestIsNotEmptyValue(): array
    {
        return [
            [
                new TimeValue(3661),
            ],
        ];
    }

    protected static function getValidSearchValueOne()
    {
        return new TimeValue(static::getSearchTargetValueOne());
    }

    protected static function getValidSearchValueTwo()
    {
        return new TimeValue(static::getSearchTargetValueTwo());
    }

    protected static function getSearchTargetValueOne(): int
    {
        return 9600;
    }

    protected static function getSearchTargetValueTwo(): int
    {
        return 14400;
    }
}
