<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
return [
    'ezurlalias_ml' => [
        0 => [
            'action' => 'eznode:2',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '1',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '3',
            'link' => '1',
            'parent' => '0',
            'text' => '',
            'text_md5' => 'd41d8cd98f00b204e9800998ecf8427e',
        ],
        1 => [
            'action' => 'eznode:314',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '4',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '2',
            'link' => '2',
            'parent' => '0',
            'text' => 'jedan',
            'text_md5' => '6896260129051a949051c3847c34466f',
        ],
        2 => [
            'action' => 'eznode:315',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '5',
            'is_alias' => '0',
            'is_original' => '0',
            'lang_mask' => '2',
            'link' => '3',
            'parent' => '0',
            'text' => 'dva',
            'text_md5' => 'c67ed9a09ab136fae610b6a087d82e21',
        ],
        3 => [
            'action' => 'eznode:314',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '2',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '2',
            'parent' => '0',
            'text' => 'jedan-new',
            'text_md5' => '0d1c74fb1d039ba5026253965a293325',
        ],
        4 => [
            'action' => 'eznode:315',
            'action_type' => 'eznode',
            'alias_redirects' => '1',
            'id' => '3',
            'is_alias' => '0',
            'is_original' => '1',
            'lang_mask' => '2',
            'link' => '3',
            'parent' => '0',
            'text' => 'dva-new',
            'text_md5' => '8b9bbf68d41279d4db7c0d6c4be1ad25',
        ],
    ],
    'ezcontent_language' => [
        0 => [
            'disabled' => 0,
            'id' => 2,
            'locale' => 'cro-HR',
            'name' => 'Croatian (Hrvatski)',
        ],
    ],
    'ezurlalias_ml_incr' => [
        0 => [
            'id' => '1',
        ],
        1 => [
            'id' => '2',
        ],
        2 => [
            'id' => '3',
        ],
        3 => [
            'id' => '4',
        ],
        4 => [
            'id' => '5',
        ],
    ],
    'ezcontentobject_tree' => [
        0 => [
            'node_id' => 2,
            'main_node_id' => 2,
            'parent_node_id' => 1,
            'path_string' => '',
            'path_identification_string' => '',
            'remote_id' => '',
            'contentobject_id' => 1,
        ],
        1 => [
            'node_id' => 314,
            'main_node_id' => 314,
            'parent_node_id' => 2,
            'path_string' => '',
            'path_identification_string' => '',
            'remote_id' => '',
            'contentobject_id' => 2,
        ],
        2 => [
            'node_id' => 315,
            'main_node_id' => 315,
            'parent_node_id' => 2,
            'path_string' => '',
            'path_identification_string' => '',
            'remote_id' => '',
            'contentobject_id' => 3,
        ],
    ],
    'ezcontentobject' => [
        0 => [
            'id' => 2,
            'initial_language_id' => 2,
            'current_version' => 1,
            'contentclass_id' => 1,
        ],
        1 => [
            'id' => 3,
            'initial_language_id' => 2,
            'current_version' => 1,
            'contentclass_id' => 2,
        ],
    ],
    'ezcontentobject_name' => [
        0 => [
            'contentobject_id' => 2,
            'content_version' => 1,
            'name' => 'dva new',
            'content_translation' => 'cro-HR',
        ],
        1 => [
            'contentobject_id' => 3,
            'content_version' => 1,
            'name' => 'jedan new',
            'content_translation' => 'cro-HR',
        ],
    ],
    'ezcontentclass' => [
        0 => [
            'id' => 1,
            'version' => '0',
            'always_available' => 0,
            'contentobject_name' => '<short_name|name>',
            'created' => '1033917596',
            'creator_id' => 14,
            'identifier' => 'folder',
            'initial_language_id' => 2,
            'is_container' => true,
            'language_mask' => 2,
            'modified' => '1311154215',
            'modifier_id' => 14,
            'remote_id' => '5fcdb3fb687dd6dcf8c94bc84e8bd1b2',
            'serialized_description_list' => 'a:0:{}',
            'serialized_name_list' => 'a:1:{s:6:"eng-GB";s:6:"Folder";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => null,
        ],
        1 => [
            'id' => 2,
            'version' => '0',
            'always_available' => 1,
            'contentobject_name' => '<name>',
            'created' => '1033917896',
            'creator_id' => 14,
            'identifier' => 'user_group',
            'initial_language_id' => 2,
            'is_container' => true,
            'language_mask' => 2,
            'modified' => '1311154815',
            'modifier_id' => 14,
            'remote_id' => '0f2622aad22267e195c8e76b05c25e29',
            'serialized_description_list' => 'a:0:{}',
            'serialized_name_list' => 'a:2:{s:6:"eng-GB";s:10:"User group";s:16:"always-available";s:6:"eng-GB";}',
            'sort_field' => 1,
            'sort_order' => 1,
            'url_alias_name' => null,
        ],
    ],
];
