<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Tests\Bundle\Core\Routing;

use Ibexa\Bundle\Core\Routing\DefaultRouter;
use Ibexa\Bundle\Core\SiteAccess\Matcher;
use Ibexa\Core\MVC\Symfony\Routing\SimplifiedRequest;
use Ibexa\Core\MVC\Symfony\SiteAccess;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Routing\Router as FrameworkRouter;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Exception\InvalidParameterException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Router;

/**
 * @covers \Ibexa\Bundle\Core\Routing\DefaultRouter
 */
final class DefaultRouterTest extends TestCase
{
    private const array NON_SITEACCESS_AWARE_ROUTES = ['_dontwantsiteaccess'];

    private Router&MockObject $innerRouter;

    private SiteAccess\SiteAccessRouterInterface&MockObject $siteAccessRouter;

    private RequestContext $requestContext;

    protected function setUp(): void
    {
        parent::setUp();
        $this->innerRouter = $this->createMock(Router::class);
        $this->siteAccessRouter = $this->createMock(SiteAccess\SiteAccessRouterInterface::class);
        $this->requestContext = new RequestContext();
        $this->innerRouter->method('getContext')->willReturnCallback(fn (): RequestContext => $this->requestContext);
    }

    private function createRouter(): DefaultRouter
    {
        return new DefaultRouter($this->innerRouter, $this->siteAccessRouter, self::NON_SITEACCESS_AWARE_ROUTES);
    }

    public function testMatchRequestWithSemanticPathinfo(): void
    {
        $pathinfo = '/siteaccess/foo/bar';
        $semanticPathinfo = '/foo/bar';
        $request = Request::create($pathinfo);
        $request->attributes->set('semanticPathinfo', $semanticPathinfo);
        $matchedParameters = ['_controller' => 'AcmeBundle:myAction'];

        $this->innerRouter
            ->expects(self::once())
            ->method('matchRequest')
            ->with(self::callback(
                static fn (Request $matchedRequest): bool => $matchedRequest->getPathInfo() === $semanticPathinfo
            ))
            ->willReturn($matchedParameters);

        self::assertSame($matchedParameters, $this->createRouter()->matchRequest($request));
        // The original request must not be altered
        self::assertSame($pathinfo, $request->getPathInfo());
    }

    public function testMatchRequestRegularPathinfo(): void
    {
        $matchedParameters = ['_controller' => 'AcmeBundle:myAction'];
        $request = Request::create('/siteaccess/foo/bar');

        $this->innerRouter
            ->expects(self::once())
            ->method('matchRequest')
            ->with(self::identicalTo($request))
            ->willReturn($matchedParameters);

        self::assertSame($matchedParameters, $this->createRouter()->matchRequest($request));
    }

    /**
     * @dataProvider providerGenerateNoSiteAccess
     */
    public function testGenerateNoSiteAccess(string $url): void
    {
        $this->innerRouter
            ->expects(self::once())
            ->method('generate')
            ->with(__METHOD__)
            ->willReturn($url);

        self::assertSame($url, $this->createRouter()->generate(__METHOD__));
    }

    /**
     * @return iterable<array{string}>
     */
    public function providerGenerateNoSiteAccess(): iterable
    {
        return [
            ['/foo/bar'],
            ['/foo/bar/baz?truc=muche&tata=toto'],
            ['http://ibexa.co/Products/Ibexa-CMS'],
            ['http://www.metalfrance.net/decouvertes/edge-caress-inverse-ep'],
        ];
    }

    /**
     * @dataProvider providerGenerateWithSiteAccess
     *
     * @param string $urlGenerated The URL generated by the standard UrLGenerator
     * @param string $relevantUri The relevant URI part of the generated URL (without host and basepath)
     * @param string $expectedUrl The URL we're expecting to be finally generated, with siteaccess
     * @param string $saName The SiteAccess name
     * @param bool $isMatcherLexer True if the siteaccess matcher is URILexer
     * @param int $referenceType The type of reference to be generated (one of the constants)
     */
    public function testGenerateWithSiteAccess(
        string $urlGenerated,
        string $relevantUri,
        string $expectedUrl,
        string $saName,
        bool $isMatcherLexer,
        int $referenceType,
        ?string $routeName
    ): void {
        $routeName = $routeName ?: __METHOD__;
        $this->innerRouter
            ->expects(self::once())
            ->method('generate')
            ->with($routeName)
            ->willReturn($urlGenerated);

        // If matcher is URILexer, we make it act as it's supposed to, prepending the siteaccess.
        if ($isMatcherLexer) {
            $matcher = $this->createMock(SiteAccess\URILexer::class);
            // Route is siteaccess aware, we're expecting analyseLink() to be called
            if (!in_array($routeName, self::NON_SITEACCESS_AWARE_ROUTES, true)) {
                $matcher
                    ->expects(self::once())
                    ->method('analyseLink')
                    ->with($relevantUri)
                    ->willReturn("/$saName$relevantUri");
            } else {
                // Non-siteaccess aware route, it's not supposed to be analysed
                $matcher
                    ->expects(self::never())
                    ->method('analyseLink');
            }
        } else {
            $matcher = $this->createMock(Matcher::class);
        }

        $urlComponents = parse_url($urlGenerated);
        if (isset($urlComponents['host'])) {
            $this->requestContext->setHost($urlComponents['host']);
            $this->requestContext->setScheme($urlComponents['scheme']);
            if (isset($urlComponents['port']) && $urlComponents['scheme'] === 'http') {
                $this->requestContext->setHttpPort($urlComponents['port']);
            } elseif (isset($urlComponents['port']) && $urlComponents['scheme'] === 'https') {
                $this->requestContext->setHttpsPort($urlComponents['port']);
            }
        }
        $this->requestContext->setBaseUrl(
            substr($urlComponents['path'], 0, strpos($urlComponents['path'], $relevantUri))
        );

        $router = $this->createRouter();
        $router->setSiteAccess(new SiteAccess($saName, 'test', $matcher));

        self::assertSame($expectedUrl, $router->generate($routeName, [], $referenceType));
    }

    /**
     * @return iterable<array{string, string, string, string, bool, int, string|null}>
     */
    public function providerGenerateWithSiteAccess(): iterable
    {
        return [
            ['/foo/bar', '/foo/bar', '/foo/bar', 'test_siteaccess', false, UrlGeneratorInterface::ABSOLUTE_PATH, null],
            ['http://ezpublish.dev/foo/bar', '/foo/bar', 'http://ezpublish.dev/foo/bar', 'test_siteaccess', false, UrlGeneratorInterface::ABSOLUTE_URL, null],
            ['http://ezpublish.dev/foo/bar', '/foo/bar', 'http://ezpublish.dev/test_siteaccess/foo/bar', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, null],
            ['http://ezpublish.dev/foo/bar', '/foo/bar', 'http://ezpublish.dev/foo/bar', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, '_dontwantsiteaccess'],
            ['http://ezpublish.dev:8080/foo/bar', '/foo/bar', 'http://ezpublish.dev:8080/test_siteaccess/foo/bar', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, null],
            ['http://ezpublish.dev:8080/foo/bar', '/foo/bar', 'http://ezpublish.dev:8080/foo/bar', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, '_dontwantsiteaccess'],
            ['https://ezpublish.dev/secured', '/secured', 'https://ezpublish.dev/test_siteaccess/secured', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, null],
            ['https://ezpublish.dev:445/secured', '/secured', 'https://ezpublish.dev:445/test_siteaccess/secured', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, null],
            ['http://ezpublish.dev:8080/foo/root_folder/bar/baz', '/bar/baz', 'http://ezpublish.dev:8080/foo/root_folder/test_siteaccess/bar/baz', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_URL, null],
            ['/foo/bar/baz', '/foo/bar/baz', '/test_siteaccess/foo/bar/baz', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_PATH, null],
            ['/foo/root_folder/bar/baz', '/bar/baz', '/foo/root_folder/test_siteaccess/bar/baz', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_PATH, null],
            ['/foo/bar/baz', '/foo/bar/baz', '/foo/bar/baz', 'test_siteaccess', true, UrlGeneratorInterface::ABSOLUTE_PATH, '_dontwantsiteaccess'],
        ];
    }

    public function testGenerateReverseSiteAccessMatch(): void
    {
        $routeName = 'some_route_name';
        $urlGenerated = 'http://phoenix-rises.fm/foo/bar';

        $siteAccessName = 'foo_test';
        $contexts = [];
        $this->expectReverseSiteAccessMatch(
            $siteAccessName,
            new SimplifiedRequest('http', 'phoenix-rises.fm'),
            $contexts
        );
        $this->innerRouter
            ->expects(self::once())
            ->method('generate')
            ->with($routeName, [])
            ->willReturn($urlGenerated);

        $router = $this->createRouter();
        $router->setSiteAccess(new SiteAccess('test', 'test', $this->createMock(Matcher::class)));

        self::assertSame(
            $urlGenerated,
            $router->generate($routeName, ['siteaccess' => $siteAccessName], DefaultRouter::ABSOLUTE_PATH)
        );

        // Context is switched to the target SiteAccess for generation, then restored
        self::assertCount(2, $contexts);
        self::assertSame('phoenix-rises.fm', $contexts[0]->getHost());
        self::assertNotSame($this->requestContext, $contexts[0]);
        self::assertSame($this->requestContext, $contexts[1]);
    }

    public function testGenerateRestoresContextWhenInnerRouterThrows(): void
    {
        $siteAccessName = 'foo_test';
        $contexts = [];
        $this->expectReverseSiteAccessMatch(
            $siteAccessName,
            new SimplifiedRequest('https', 'example.com'),
            $contexts
        );
        $this->innerRouter
            ->expects(self::once())
            ->method('generate')
            ->willThrowException(new InvalidParameterException());

        $this->expectException(InvalidParameterException::class);
        try {
            $this->createRouter()->generate('route', ['siteaccess' => $siteAccessName]);
        } finally {
            self::assertCount(2, $contexts);
            self::assertNotSame($this->requestContext, $contexts[0]);
            self::assertSame($this->requestContext, $contexts[1]);
        }
    }

    public function testWarmUpDelegatesToInnerRouter(): void
    {
        $innerRouter = $this->createMock(FrameworkRouter::class);
        $innerRouter
            ->expects(self::once())
            ->method('warmUp')
            ->with('/cache', '/build')
            ->willReturn(['/cache/routes.php']);

        $router = new DefaultRouter($innerRouter, $this->siteAccessRouter);

        self::assertSame(['/cache/routes.php'], $router->warmUp('/cache', '/build'));
    }

    public function testWarmUpDoesNothingWhenInnerRouterIsNotWarmable(): void
    {
        self::assertSame([], $this->createRouter()->warmUp('/cache', '/build'));
    }

    /**
     * @dataProvider providerGetContextBySimplifiedRequest
     */
    public function testGetContextBySimplifiedRequest(string $uri): void
    {
        self::assertEquals(
            $this->getExpectedRequestContext($uri),
            $this->createRouter()->getContextBySimplifiedRequest(SimplifiedRequest::fromUrl($uri))
        );
    }

    /**
     * @return iterable<array{string}>
     */
    public function providerGetContextBySimplifiedRequest(): iterable
    {
        return [
            ['/foo/bar'],
            ['http://ezpublish.dev/foo/bar'],
            ['http://ezpublish.dev:8080/foo/bar'],
            ['https://ezpublish.dev/secured'],
            ['https://ezpublish.dev:445/secured'],
            ['http://ezpublish.dev:8080/foo/root_folder/bar/baz'],
        ];
    }

    /**
     * @param \Symfony\Component\Routing\RequestContext[] $contexts
     */
    private function expectReverseSiteAccessMatch(
        string $siteAccessName,
        SimplifiedRequest $simplifiedRequest,
        array &$contexts
    ): void {
        $versatileMatcher = $this->createMock(SiteAccess\VersatileMatcher::class);
        $versatileMatcher
            ->expects(self::once())
            ->method('getRequest')
            ->willReturn($simplifiedRequest);
        $this->siteAccessRouter
            ->expects(self::once())
            ->method('matchByName')
            ->with($siteAccessName)
            ->willReturn(new SiteAccess($siteAccessName, 'foo', $versatileMatcher));
        $this->innerRouter
            ->expects(self::exactly(2))
            ->method('setContext')
            ->willReturnCallback(static function (RequestContext $context) use (&$contexts): void {
                $contexts[] = $context;
            });
    }

    private function getExpectedRequestContext(string $uri): RequestContext
    {
        $requestContext = new RequestContext();
        $uriComponents = parse_url($uri);
        if (isset($uriComponents['host'])) {
            $requestContext->setHost($uriComponents['host']);
            $requestContext->setScheme($uriComponents['scheme']);
            if (isset($uriComponents['port']) && $uriComponents['scheme'] === 'http') {
                $requestContext->setHttpPort($uriComponents['port']);
            } elseif (isset($uriComponents['port']) && $uriComponents['scheme'] === 'https') {
                $requestContext->setHttpsPort($uriComponents['port']);
            }
        }
        if (isset($uriComponents['path'])) {
            $requestContext->setPathInfo($uriComponents['path']);
        }

        return $requestContext;
    }
}
