services:
    Ibexa\Bundle\LegacySearchEngine\ApiLoader\ConnectionFactory:
        arguments:
            $container: '@service_container'
            $repositoryConfigurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'

    ibexa.api.search_engine.legacy.connection:
        class: Doctrine\DBAL\Connection
        factory: ['@Ibexa\Bundle\LegacySearchEngine\ApiLoader\ConnectionFactory', getConnection]
        lazy: true
