services:
    Ibexa\Bundle\LegacySearchEngine\ApiLoader\ConnectionFactory:
        arguments:
            $repositoryConfigurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'
        calls:
            - [setContainer, ['@service_container']]

    ibexa.api.search_engine.legacy.connection:
        class: Doctrine\DBAL\Connection
        factory: ['@Ibexa\Bundle\LegacySearchEngine\ApiLoader\ConnectionFactory', getConnection]
        lazy: true
