<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
return [
  0 => [
    'ibexa_content_version_id' => '439',
    'ibexa_content_version_version' => '1',
    'ibexa_content_version_modified' => '1033920746',
    'ibexa_content_version_creator_id' => '14',
    'ibexa_content_version_created' => '1033920737',
    'ibexa_content_version_status' => '3',
    'ibexa_content_version_initial_language_id' => '2',
    'ibexa_content_version_language_mask' => '3',
    'ibexa_content_tree_main_node_id' => '12',
    'ibexa_content_id' => '11',
    'ibexa_content_contentclass_id' => '3',
    'ibexa_content_section_id' => '2',
    'ibexa_content_owner_id' => '14',
    'ibexa_content_remote_id' => '5f7f0bdb3381d6a461d8c29ff53d908f',
    'ibexa_content_current_version' => '2',
    'ibexa_content_initial_language_id' => '2',
    'ibexa_content_modified' => '1311154215',
    'ibexa_content_published' => '1033920746',
    'ibexa_content_status' => '1',
    'ibexa_content_name' => 'Members',
    'ibexa_content_language_mask' => '3',
    'ibexa_content_is_hidden' => '0',
    'ibexa_content_version_contentobject_id' => '11',
  ],
  1 => [
    'ibexa_content_version_id' => '674',
    'ibexa_content_version_version' => '2',
    'ibexa_content_version_modified' => '1311154215',
    'ibexa_content_version_creator_id' => '14',
    'ibexa_content_version_created' => '1311154215',
    'ibexa_content_version_status' => '1',
    'ibexa_content_version_initial_language_id' => '2',
    'ibexa_content_version_language_mask' => '3',
    'ibexa_content_tree_main_node_id' => '12',
    'ibexa_content_id' => '11',
    'ibexa_content_contentclass_id' => '3',
    'ibexa_content_section_id' => '2',
    'ibexa_content_owner_id' => '14',
    'ibexa_content_remote_id' => '5f7f0bdb3381d6a461d8c29ff53d908f',
    'ibexa_content_current_version' => '2',
    'ibexa_content_initial_language_id' => '2',
    'ibexa_content_modified' => '1311154215',
    'ibexa_content_published' => '1033920746',
    'ibexa_content_status' => '1',
    'ibexa_content_name' => 'Members',
    'ibexa_content_language_mask' => '3',
    'ibexa_content_is_hidden' => '0',
    'ibexa_content_version_contentobject_id' => '11',
  ],
];
