<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Bundle\RepositoryInstaller\Migration;

use DateTimeImmutable;
use Doctrine\DBAL\Schema\Schema;
use Ibexa\Contracts\DoctrineMigrations\Migrations\AbstractSqlMigration;
use Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationInterface;
use Ibexa\Contracts\DoctrineMigrations\Migrations\SqlPlatform;

/**
 * Turns the SERIAL columns of the core tables into identity columns on PostgreSQL, as a fresh 6.0
 * install creates them.
 *
 * Doctrine DBAL 4 creates an autoincrement column on PostgreSQL as GENERATED BY DEFAULT AS
 * IDENTITY, where DBAL 2 and 3 used SERIAL: a column defaulting to the next value of its own
 * sequence. The install migrations, which a 6.0 install runs too, are the ones from 4.6 and 5.0, so
 * they created these as SERIAL, and a database upgraded from 5.0 keeps them.
 * sql/convert-serial-columns-to-identity-postgresql.sql turns each SERIAL column into an identity
 * column that carries on from its sequence's current value, drops the old sequence, and skips a
 * column that's no longer SERIAL.
 *
 * This is kept apart from the other 6.0 migrations on purpose: SERIAL columns work the same for
 * inserts, so leaving this one out keeps them as they are.
 */
final class ConvertPostgreSqlSerialColumnsToIdentityMigration extends AbstractSqlMigration implements IbexaMigrationInterface
{
    public function getDescription(): string
    {
        return 'Turns the core SERIAL columns into identity columns on PostgreSQL';
    }

    public static function getTargetVersion(): string
    {
        return '6.0.0';
    }

    public static function getCreationDate(): DateTimeImmutable
    {
        return new DateTimeImmutable('2026-10-06 00:00:03');
    }

    public function up(Schema $schema): void
    {
        $this->abortIfUnsupportedPlatform(SqlPlatform::MYSQL, SqlPlatform::MARIADB, SqlPlatform::POSTGRESQL, SqlPlatform::SQLITE);

        if ($this->isPostgreSQL()) {
            $this->addSqlFile(__DIR__ . '/sql/convert-serial-columns-to-identity-postgresql.sql');
        }
    }
}
