parameters:
    # Constant authentication execution time in seconds (float). Blocks timing attacks.
    # Must be larger than expected real execution time, with a good margin.
    # If set to zero, constant time authentication is disabled. Do not do this on production environments.
    ibexa.security.authentication.constant_auth_time: 1.0

services:
    Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider:
        class: Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    Ibexa\Core\MVC\Symfony\Security\User\EmailProvider:
        class: Ibexa\Core\MVC\Symfony\Security\User\EmailProvider
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    Ibexa\Core\MVC\Symfony\Security\UserChecker:
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'

    Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter:
        class: Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter:
        class: Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    Ibexa\Core\MVC\Symfony\Controller\SecurityController:
        public: true
        class: Ibexa\Core\MVC\Symfony\Controller\SecurityController
        arguments: ["@twig", '@ibexa.config.resolver', "@security.authentication_utils"]

    ibexa.security.user_provider: '@Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider'
    ibexa.security.user_provider.username: '@Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider'
    ibexa.security.user_provider.email: '@Ibexa\Core\MVC\Symfony\Security\User\EmailProvider'

    Ibexa\Core\MVC\Symfony\Security\Authentication\EventSubscriber\RepositoryUserAuthenticationSubscriber:
        autowire: true
        autoconfigure: true
        arguments:
            $constantAuthTime: '%ibexa.security.authentication.constant_auth_time%'

    Ibexa\Core\MVC\Symfony\Security\Authentication\EventSubscriber\OnAuthenticationTokenCreatedRepositoryUserSubscriber:
        autowire: true
        autoconfigure: true
