services:
    Ibexa\Bundle\Core\ApiLoader\RepositoryConfigurationProvider:
        deprecated:
            package: 'ibexa/core'
            version: '5.0'
            message: 'Since ibexa/core 5.0: The "%service_id%" service is deprecated and will be removed in 6.0. Use Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface instead'
        arguments:
            $configurationProvider: '@Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface'

    Ibexa\Bundle\Core\ApiLoader\StorageConnectionFactory:
        autowire: true
        autoconfigure: true
        arguments:
            $serviceLocator: ~

    ibexa.persistence.connection:
        public: true # @todo should be private
        class: Doctrine\DBAL\Connection
        factory: ['@Ibexa\Bundle\Core\ApiLoader\StorageConnectionFactory', getConnection]
        lazy: true

    # Legacy storage engine
    ibexa.api.storage_engine.legacy:
        alias: Ibexa\Core\Persistence\Legacy\Handler
