name: Build and publish Solr Docker image
on:
    workflow_dispatch: ~

env:
  IMAGE_NAME: ghcr.io/ibexa/core/solr

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
          packages: write
        steps:
            - uses: actions/checkout@v3
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build image
              run: docker build -t "$IMAGE_NAME:latest" docker/solr
            - name: Push image
              if: github.event_name == 'workflow_dispatch'
              run: docker push "$IMAGE_NAME"

